"""
Protocols para la capa de servicios.

Los routers dependen únicamente de estos Protocols via Depends().
Las implementaciones concretas viven en app/services/providers/<proveedor>/.
"""

from typing import Any, Dict, List, Optional, Protocol

from app.schemas.payment_methods import PaymentMethodResponse
from app.schemas.clients import (
    ClientResponse,
    ClientResolveRequest,
    ClientVerifyRequest,
)
from app.schemas.connection_status import ConnectionStatus, PingResultResponse
from app.schemas.internet_plans import InternetPlanListItem
from app.schemas.tickets import TicketCreateRequest, TicketResponse


class ClientService(Protocol):
    async def get_by_document(self, document: str) -> Optional[ClientResponse]: ...
    async def get_by_phone(self, phone: str) -> Optional[ClientResponse]: ...
    async def get_by_service_id(self, service_id: str) -> Optional[ClientResponse]: ...
    async def search(self, query: str) -> List[ClientResponse]: ...
    async def get_all(self) -> List[ClientResponse]: ...
    async def resolve(self, request: ClientResolveRequest) -> ClientResponse: ...
    async def verify(
        self, service_id: int, request: ClientVerifyRequest
    ) -> Dict[str, Any]: ...
    async def update(self, service_id: int, update_data: Dict[str, Any]) -> bool: ...


class TicketService(Protocol):
    async def create(self, request: TicketCreateRequest) -> TicketResponse: ...
    async def get(self, ticket_id: int) -> Optional[TicketResponse]: ...
    async def zone_is_blocked(self, zone_id: int) -> bool: ...


class InternetPlanService(Protocol):
    async def list_plans(self) -> Optional[List[InternetPlanListItem]]: ...
    async def get_plan_detail(self, plan_id: int) -> Any: ...


class NetworkService(Protocol):
    async def start_ping(self, service_id: int, pings: int) -> Optional[str]: ...
    async def get_ping_result(self, task_id: str) -> PingResultResponse: ...


class PaymentMethodService(Protocol):
    async def list_payment_methods(self) -> Optional[List[PaymentMethodResponse]]: ...
